// Generated by tools/recover_character_forward_shader.py; do not edit.
// Original no-keyword programs 6/14/18/22/26. Runtime rejects other material keywords.
Shader "OpenWDS/ScarabCharacter"
{
Properties {
_Brightness ("Brightness", Float) = 1.0
[NoScaleOffset]_MainTex ("Main Tex", 2D) = "white" {}
[NoScaleOffset]_MaskTex ("Mask Tex", 2D) = "black" {}
_Light_Angle ("Light Angle", Vector) = (0.0, 0.0, 0.0, 0.0)
_Shadow_Threshould ("Shadow Threshould", Range(0.0, 1.0)) = 0.5
_1 ("Shadow Softness", Range(0.0, 1.0)) = 0.0
_Shadow_Color ("Shadow Color", Color) = (0.0, 0.0, 0.0, 0.0)
[ToggleUI]_Is_Eye ("Is Eye", Float) = 0.0
[HDR]_Rim_Color ("Rim Color", Color) = (0.0, 0.0, 0.0, 0.0)
_RimStrength ("Rim Strength", Range(0.0, 1.0)) = 1.0
_RimStrength_3 ("Specular Brightness", Range(0.0, 1.0)) = 0.0
_RimPower ("Rim Power", Range(0.0, 5.0)) = 1.0
_LightDirectionStrength ("Light Direction Strength", Range(0.0, 1.0)) = 1.0
_RimThreshould ("RimThreshould", Range(0.0, 1.5)) = 0.75
_RimSoftness ("RimSoftness", Range(0.0, 1.0)) = 0.0
_ambientColor ("ambientColor", Color) = (0.0, 0.0, 0.0, 0.0)
_ambientIntensity ("ambientIntensity", Range(0.0, 1.0)) = 1.0
[NoScaleOffset]_MaskTex_3 ("Matcap Metallic Tex", 2D) = "black" {}
_PrimaryLightIntensity ("PrimaryLightIntensity", Float) = 1.0
_PrimaryLightDirection ("PrimaryLightDirection", Vector) = (0.0, 0.0, 1.0, 0.0)
_PrimaryLightColor ("PrimaryLightColor", Vector) = (1.0, 1.0, 1.0, 0.0)
[HideInInspector]_CastShadows ("_CastShadows", Float) = 0.0
[HideInInspector]_Surface ("_Surface", Float) = 0.0
[HideInInspector]_Blend ("_Blend", Float) = 0.0
[HideInInspector]_AlphaClip ("_AlphaClip", Float) = 0.0
[HideInInspector]_SrcBlend ("_SrcBlend", Float) = 1.0
[HideInInspector]_DstBlend ("_DstBlend", Float) = 0.0
[ToggleUI][HideInInspector]_ZWrite ("_ZWrite", Float) = 1.0
[HideInInspector]_ZWriteControl ("_ZWriteControl", Float) = 0.0
[HideInInspector]_ZTest ("_ZTest", Float) = 4.0
[HideInInspector]_Cull ("_Cull", Float) = 2.0
[HideInInspector]_QueueOffset ("_QueueOffset", Float) = 0.0
[HideInInspector]_QueueControl ("_QueueControl", Float) = -1.0
[HideInInspector][NoScaleOffset]unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
[HideInInspector][NoScaleOffset]unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
[HideInInspector][NoScaleOffset]unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
}
SubShader {
Tags { "RenderPipeline"="UniversalPipeline" "RenderType"="Opaque" "Queue"="Geometry" }
Pass {
Name "Universal Forward"
Tags { "LightMode"="UniversalForward" }
Blend [_SrcBlend] [_DstBlend], [_SrcBlend] [_DstBlend]
ZTest [_ZTest]
ZWrite [_ZWrite]
Cull [_Cull]
HLSLPROGRAM
#pragma target 4.5
#pragma vertex vert
#pragma fragment frag
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
CBUFFER_START(UnityPerMaterial)
float4 _MaskTex_3_TexelSize;
float _1;
float _Is_Eye;
float4 _Rim_Color;
float _RimStrength_3;
float4 _MainTex_TexelSize;
float4 _MaskTex_TexelSize;
float _RimStrength;
float _RimPower;
float _LightDirectionStrength;
float3 _Light_Angle;
float4 _Shadow_Color;
float _Brightness;
float _Shadow_Threshould;
float3 _PrimaryLightDirection;
float3 _PrimaryLightColor;
float _PrimaryLightIntensity;
float _RimThreshould;
float _RimSoftness;
float4 _ambientColor;
float _ambientIntensity;
CBUFFER_END




static float4 gl_Position;
static float3 vert_11;
static float4 vert_94;
static float4 vert_96;
static float3 vert_98;
static float4 vert_153;
static float3 vert_167;
static float3 vert_175;
static float3 vert_190;

struct vert_Input
{
    float3 vert_11 : POSITION;
    float3 vert_98 : NORMAL;
    float4 vert_96 : TEXCOORD0;
};

struct vert_Output
{
    float4 vert_94 : TEXCOORD0;
    float4 vert_153 : TEXCOORD1;
    float3 vert_167 : TEXCOORD2;
    float3 vert_190 : TEXCOORD3;
    float3 vert_175 : TEXCOORD4;
    float4 gl_Position : SV_Position;
};

static float3 vert_9;
static float4 vert_58;
static float vert_119;
static float3 vert_137;
static bool vert_184;

void vert_main()
{
    vert_9 = vert_11.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_11.xxx) + vert_9;
    vert_9 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_11.zzz) + vert_9;
    vert_9 += transpose(UNITY_MATRIX_M)[3].xyz;
    vert_58 = vert_9.yyyy * transpose(UNITY_MATRIX_VP)[1];
    vert_58 = (transpose(UNITY_MATRIX_VP)[0] * vert_9.xxxx) + vert_58;
    vert_58 = (transpose(UNITY_MATRIX_VP)[2] * vert_9.zzzz) + vert_58;
    gl_Position = vert_58 + transpose(UNITY_MATRIX_VP)[3];
    vert_94 = vert_96;
    vert_58.x = dot(vert_98, transpose(UNITY_MATRIX_I_M)[0].xyz);
    vert_58.y = dot(vert_98, transpose(UNITY_MATRIX_I_M)[1].xyz);
    vert_58.z = dot(vert_98, transpose(UNITY_MATRIX_I_M)[2].xyz);
    vert_119 = dot(vert_58.xyz, vert_58.xyz);
    vert_119 = max(vert_119, 1.1754943508222875079687365372222e-38f);
    vert_119 = rsqrt(vert_119);
    float3 vert_134 = vert_119.xxx * vert_58.xyz;
    vert_58 = float4(vert_134.x, vert_134.y, vert_134.z, vert_58.w);
    vert_137 = _Light_Angle + _PrimaryLightDirection;
    vert_119 = dot(vert_58.xyz, vert_137);
    vert_153.y = (vert_119 * 0.5f) + 0.5f;
    vert_153.x = dot(_PrimaryLightDirection, vert_58.xyz);
    vert_167 = vert_58.xyz;
    vert_153 = float4(vert_153.x, vert_153.y, 0.0f.xx.x, 0.0f.xx.y);
    vert_175 = vert_9;
    vert_9 = (-vert_9) + _WorldSpaceCameraPos;
    vert_184 = unity_OrthoParams.w == 0.0f;
    float vert_193;
    if (vert_184)
    {
        vert_193 = vert_9.x;
    }
    else
    {
        vert_193 = transpose(UNITY_MATRIX_V)[0].z;
    }
    vert_190.x = vert_193;
    float vert_204;
    if (vert_184)
    {
        vert_204 = vert_9.y;
    }
    else
    {
        vert_204 = transpose(UNITY_MATRIX_V)[1].z;
    }
    vert_190.y = vert_204;
    float vert_215;
    if (vert_184)
    {
        vert_215 = vert_9.z;
    }
    else
    {
        vert_215 = transpose(UNITY_MATRIX_V)[2].z;
    }
    vert_190.z = vert_215;

}

vert_Output vert(vert_Input stage_input)
{
    vert_11 = stage_input.vert_11;
    vert_96 = stage_input.vert_96;
    vert_98 = stage_input.vert_98;
    vert_main();
    vert_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vert_94 = vert_94;
    stage_output.vert_153 = vert_153;
    stage_output.vert_167 = vert_167;
    stage_output.vert_175 = vert_175;
    stage_output.vert_190 = vert_190;
    return stage_output;
}



Texture2D<float4> _MainTex;
SamplerState sampler_MainTex;
Texture2D<float4> _MaskTex;
SamplerState sampler_MaskTex;
Texture2D<float4> _MaskTex_3;
SamplerState sampler_MaskTex_3;

static float4 frag_36;
static float4 frag_385;
static float3 frag_586;
static float3 frag_596;
static float4 frag_780;

struct frag_Input
{
    float4 frag_36 : TEXCOORD0;
    float4 frag_385 : TEXCOORD1;
    float3 frag_596 : TEXCOORD2;
    float3 frag_586 : TEXCOORD3;
};

struct frag_Output
{
    float4 frag_780 : SV_Target0;
};

static float4 frag_9;
static float4 frag_18;
static float3 frag_24;
static bool frag_55;
static float frag_62;
static float3 frag_120;
static float frag_134;
static float frag_145;
static bool frag_160;
static bool frag_175;
static bool frag_235;
static float frag_371;
static float3 frag_384;
static float4 frag_418;
static bool3 frag_509;
static float3 frag_518;
static float3 frag_613;
static float frag_653;
static float3 frag_758;

void frag_main()
{
    frag_9.z = -1.0f;
    frag_9.w = 0.666666686534881591796875f;
    frag_18.z = 1.0f;
    frag_18.w = -1.0f;
    frag_24 = _MainTex.SampleBias(sampler_MainTex, frag_36.xy, _GlobalMipBias.x).xyz;
    frag_55 = frag_24.y >= frag_24.z;
    frag_62 = float(frag_55);
    frag_9 = float4(frag_24.zy.x, frag_24.zy.y, frag_9.z, frag_9.w);
    float2 frag_75 = (-frag_9.xy) + frag_24.yz;
    frag_18 = float4(frag_75.x, frag_75.y, frag_18.z, frag_18.w);
    frag_9 = (frag_62.xxxx * frag_18.xywz) + frag_9.xywz;
    frag_18.z = frag_9.w;
    frag_55 = frag_24.x >= frag_9.x;
    frag_62 = float(frag_55);
    frag_9.w = frag_24.x;
    frag_18 = float4(frag_9.wyx.x, frag_9.wyx.y, frag_18.z, frag_9.wyx.z);
    frag_18 = (-frag_9) + frag_18;
    frag_9 = (frag_62.xxxx * frag_18) + frag_9;
    frag_18.x = (-frag_9.y) + frag_9.w;
    frag_120.x = min(frag_9.y, frag_9.w);
    frag_120.x = (-frag_120.x) + frag_9.x;
    frag_134 = (frag_120.x * 6.0f) + 1.0000000133514319600180897396058e-10f;
    frag_134 = frag_18.x / frag_134;
    frag_145 = frag_134 + frag_9.z;
    float3 frag_157 = abs(frag_145.xxx) + float3(-0.013888888992369174957275390625f, 0.986111104488372802734375f, -1.013888835906982421875f);
    frag_18 = float4(frag_157.x, frag_157.y, frag_157.z, frag_18.w);
    frag_160 = 1.0f < frag_18.x;
    float frag_166;
    if (frag_160)
    {
        frag_166 = frag_18.z;
    }
    else
    {
        frag_166 = frag_18.x;
    }
    frag_145 = frag_166;
    frag_175 = frag_18.x < 0.0f;
    float frag_180;
    if (frag_175)
    {
        frag_180 = frag_18.y;
    }
    else
    {
        frag_180 = frag_145;
    }
    frag_145 = frag_180;
    float3 frag_192 = frag_145.xxx + float3(1.0f, 0.666666686534881591796875f, 0.3333333432674407958984375f);
    frag_18 = float4(frag_192.x, frag_192.y, frag_192.z, frag_18.w);
    float3 frag_197 = frac(frag_18.xyz);
    frag_18 = float4(frag_197.x, frag_197.y, frag_197.z, frag_18.w);
    float3 frag_206 = (frag_18.xyz * 6.0f.xxx) + (-3.0f).xxx;
    frag_18 = float4(frag_206.x, frag_206.y, frag_206.z, frag_18.w);
    float3 frag_213 = abs(frag_18.xyz) + (-1.0f).xxx;
    frag_18 = float4(frag_213.x, frag_213.y, frag_213.z, frag_18.w);
    float3 frag_220 = clamp(frag_18.xyz, 0.0f.xxx, 1.0f.xxx);
    frag_18 = float4(frag_220.x, frag_220.y, frag_220.z, frag_18.w);
    float3 frag_225 = frag_18.xyz + (-1.0f).xxx;
    frag_18 = float4(frag_225.x, frag_225.y, frag_225.z, frag_18.w);
    frag_145 = frag_9.x + 1.0000000133514319600180897396058e-10f;
    frag_134 = frag_120.x / frag_145;
    frag_235 = frag_120.x == 0.0f;
    float frag_240;
    if (frag_235)
    {
        frag_240 = frag_9.x;
    }
    else
    {
        frag_240 = frag_145;
    }
    frag_9.x = frag_240;
    frag_120 = (frag_134.xxx * frag_18.xyz) + 1.0f.xxx;
    float3 frag_259 = frag_120 * frag_9.xxx;
    frag_18 = float4(frag_259.x, frag_259.y, frag_259.z, frag_18.w);
    frag_18.x = dot(frag_18.xyz, float3(0.21267290413379669189453125f, 0.715152204036712646484375f, 0.072175003588199615478515625f));
    float3 frag_277 = (frag_9.xxx * frag_120) + (-frag_18.xxx);
    frag_9 = float4(frag_277.x, frag_277.y, frag_277.z, frag_9.w);
    float3 frag_287 = (frag_9.xyz * 2.0f.xxx) + frag_18.xxx;
    frag_9 = float4(frag_287.x, frag_287.y, frag_287.z, frag_9.w);
    float3 frag_299 = frag_9.xyz + _RimStrength_3.xxx;
    frag_9 = float4(frag_299.x, frag_299.y, frag_299.z, frag_9.w);
    frag_134 = _PrimaryLightIntensity;
    frag_134 = clamp(frag_134, 0.0f, 1.0f);
    frag_134 *= _ambientIntensity;
    float3 frag_324 = (frag_134.xxx * _ambientColor.xyz) + _PrimaryLightColor;
    frag_18 = float4(frag_324.x, frag_324.y, frag_324.z, frag_18.w);
    float3 frag_330 = frag_18.xyz * frag_24;
    frag_18 = float4(frag_330.x, frag_330.y, frag_330.z, frag_18.w);
    frag_24 = frag_18.xyz * _Brightness.xxx;
    frag_24 *= _Shadow_Color.xyz;
    float3 frag_354 = (_Brightness.xxx * frag_18.xyz) + (-frag_24);
    frag_18 = float4(frag_354.x, frag_354.y, frag_354.z, frag_18.w);
    frag_134 = _1 * 0.5f;
    frag_134 = max(frag_134, 9.9999997473787516355514526367188e-06f);
    frag_134 = (-frag_134) + _Shadow_Threshould;
    frag_371 = (_1 * 0.5f) + _Shadow_Threshould;
    frag_371 = (-frag_134) + frag_371;
    frag_371 = 1.0f / frag_371;
    frag_384 = float3(frag_385.yx.x, frag_385.yx.y, frag_384.z);
    float2 frag_394 = clamp(frag_384.xy, 0.0f.xx, 1.0f.xx);
    frag_384 = float3(frag_394.x, frag_394.y, frag_384.z);
    frag_134 = (-frag_134) + frag_384.x;
    frag_134 = frag_371 * frag_134;
    frag_134 = clamp(frag_134, 0.0f, 1.0f);
    frag_371 = (frag_134 * (-2.0f)) + 3.0f;
    frag_134 *= frag_134;
    frag_134 *= frag_371;
    frag_418 = _MaskTex.SampleBias(sampler_MaskTex, frag_36.xy, _GlobalMipBias.x);
    frag_134 *= frag_418.x;
    float3 frag_439 = (frag_134.xxx * frag_18.xyz) + frag_24;
    frag_18 = float4(frag_439.x, frag_439.y, frag_439.z, frag_18.w);
    float3 frag_450 = (frag_9.xyz * _PrimaryLightColor) + (-frag_18.xyz);
    frag_9 = float4(frag_450.x, frag_450.y, frag_450.z, frag_9.w);
    frag_134 = frag_385.x + 0.20000000298023223876953125f;
    frag_134 = clamp(frag_134, 0.0f, 1.0f);
    frag_134 += 0.100000001490116119384765625f;
    frag_134 = frag_418.w * frag_134;
    float3 frag_474 = (frag_134.xxx * frag_9.xyz) + frag_18.xyz;
    frag_9 = float4(frag_474.x, frag_474.y, frag_474.z, frag_9.w);
    float3 frag_482 = log2(abs(_Rim_Color.xyz));
    frag_18 = float4(frag_482.x, frag_482.y, frag_482.z, frag_18.w);
    float3 frag_489 = frag_18.xyz * 0.4166666567325592041015625f.xxx;
    frag_18 = float4(frag_489.x, frag_489.y, frag_489.z, frag_18.w);
    float3 frag_494 = exp2(frag_18.xyz);
    frag_18 = float4(frag_494.x, frag_494.y, frag_494.z, frag_18.w);
    float3 frag_504 = (frag_18.xyz * 1.05499994754791259765625f.xxx) + (-0.054999999701976776123046875f).xxx;
    frag_18 = float4(frag_504.x, frag_504.y, frag_504.z, frag_18.w);
    frag_509 = bool4(float4(0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.0f).x >= _Rim_Color.xyzx.x, float4(0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.0f).y >= _Rim_Color.xyzx.y, float4(0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.0f).z >= _Rim_Color.xyzx.z, float4(0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.003130800090730190277099609375f, 0.0f).w >= _Rim_Color.xyzx.w).xyz;
    frag_518 = _Rim_Color.xyz * 12.92321014404296875f.xxx;
    float4 frag_526 = frag_18;
    float frag_530;
    if (frag_509.x)
    {
        frag_530 = frag_518.x;
    }
    else
    {
        frag_530 = frag_18.x;
    }
    frag_526.x = frag_530;
    float frag_542;
    if (frag_509.y)
    {
        frag_542 = frag_518.y;
    }
    else
    {
        frag_542 = frag_18.y;
    }
    frag_526.y = frag_542;
    float frag_554;
    if (frag_509.z)
    {
        frag_554 = frag_518.z;
    }
    else
    {
        frag_554 = frag_18.z;
    }
    frag_526.z = frag_554;
    frag_18 = frag_526;
    float3 frag_573 = (_PrimaryLightColor * frag_18.xyz) + (-frag_9.xyz);
    frag_18 = float4(frag_573.x, frag_573.y, frag_573.z, frag_18.w);
    frag_134 = _LightDirectionStrength + (-1.0f);
    frag_134 = (-frag_134) + frag_384.y;
    frag_371 = dot(frag_586, frag_586);
    frag_371 = rsqrt(frag_371);
    frag_24 = frag_371.xxx * frag_586;
    frag_371 = dot(frag_596, frag_596);
    frag_371 = sqrt(frag_371);
    frag_371 = 1.0f / frag_371;
    frag_384 = frag_371.xxx * frag_596;
    frag_371 = dot(frag_384, frag_384);
    frag_371 = rsqrt(frag_371);
    frag_613 = frag_371.xxx * frag_384;
    frag_371 = dot(frag_613, frag_24);
    frag_371 = clamp(frag_371, 0.0f, 1.0f);
    frag_371 = (-frag_371) + 1.0f;
    frag_371 = log2(frag_371);
    frag_371 *= _RimPower;
    frag_371 = exp2(frag_371);
    frag_24.x = max(_RimSoftness, 9.9999997473787516355514526367188e-06f);
    frag_24.x = (-frag_24.x) + _RimThreshould;
    frag_371 += (-frag_24.x);
    frag_653 = _RimSoftness + _RimThreshould;
    frag_24.x = (-frag_24.x) + frag_653;
    frag_24.x = 1.0f / frag_24.x;
    frag_371 *= frag_24.x;
    frag_371 = clamp(frag_371, 0.0f, 1.0f);
    frag_24.x = (frag_371 * (-2.0f)) + 3.0f;
    frag_371 *= frag_371;
    frag_371 *= frag_24.x;
    frag_371 = frag_418.z * frag_371;
    frag_134 *= frag_371;
    frag_134 *= _RimStrength;
    float3 frag_705 = (frag_134.xxx * frag_18.xyz) + frag_9.xyz;
    frag_9 = float4(frag_705.x, frag_705.y, frag_705.z, frag_9.w);
    frag_18 = float4(frag_9.xyz.x, frag_9.xyz.y, frag_9.xyz.z, frag_18.w);
    float3 frag_716 = clamp(frag_18.xyz, 0.0f.xxx, 1.0f.xxx);
    frag_18 = float4(frag_716.x, frag_716.y, frag_716.z, frag_18.w);
    float4 frag_723 = _Is_Eye.xxxx;
    frag_175 = any(bool4(0.0f.xxxx.x != frag_723.x, 0.0f.xxxx.y != frag_723.y, 0.0f.xxxx.z != frag_723.z, 0.0f.xxxx.w != frag_723.w));
    float3 frag_728;
    if (frag_175)
    {
        frag_728 = frag_18.xyz;
    }
    else
    {
        frag_728 = frag_9.xyz;
    }
    frag_9 = float4(frag_728.x, frag_728.y, frag_728.z, frag_9.w);
    frag_18.x = dot(frag_384, transpose(UNITY_MATRIX_I_V)[0].xyz);
    frag_18.y = dot(frag_384, transpose(UNITY_MATRIX_I_V)[1].xyz);
    float2 frag_755 = (frag_18.xy * 0.5f.xx) + 0.5f.xx;
    frag_18 = float4(frag_755.x, frag_755.y, frag_18.z, frag_18.w);
    frag_758 = _MaskTex_3.SampleBias(sampler_MaskTex_3, frag_18.xy, _GlobalMipBias.x).xyz;
    float3 frag_776 = (frag_758 * frag_418.yyy) + frag_9.xyz;
    frag_9 = float4(frag_776.x, frag_776.y, frag_776.z, frag_9.w);
    frag_780 = float4(frag_9.xyz.x, frag_9.xyz.y, frag_9.xyz.z, frag_780.w);
    frag_780.w = 1.0f;
}

frag_Output frag(frag_Input stage_input)
{
    frag_36 = stage_input.frag_36;
    frag_385 = stage_input.frag_385;
    frag_586 = stage_input.frag_586;
    frag_596 = stage_input.frag_596;
    frag_main();
    frag_Output stage_output;
    stage_output.frag_780 = frag_780;
    return stage_output;
}

ENDHLSL
}
Pass {
Name "DepthOnly"
Tags { "LightMode"="DepthOnly" }
ZTest LEqual
ZWrite On
Cull [_Cull]
ColorMask 0
HLSLPROGRAM
#pragma target 4.5
#pragma vertex vert
#pragma fragment frag
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
float4 _ShadowBias;
float3 _LightDirection;
CBUFFER_START(UnityPerMaterial)
float4 _MaskTex_3_TexelSize;
float _1;
float _Is_Eye;
float4 _Rim_Color;
float _RimStrength_3;
float4 _MainTex_TexelSize;
float4 _MaskTex_TexelSize;
float _RimStrength;
float _RimPower;
float _LightDirectionStrength;
float3 _Light_Angle;
float4 _Shadow_Color;
float _Brightness;
float _Shadow_Threshould;
float3 _PrimaryLightDirection;
float3 _PrimaryLightColor;
float _PrimaryLightIntensity;
float _RimThreshould;
float _RimSoftness;
float4 _ambientColor;
float _ambientIntensity;
CBUFFER_END



static float4 gl_Position;
static float3 vert_12;
static float4 vert_103;
static float4 vert_105;

struct vert_Input
{
    float3 vert_12 : POSITION;
    float4 vert_105 : TEXCOORD0;
};

struct vert_Output
{
    float4 vert_103 : TEXCOORD0;
    float4 gl_Position : SV_Position;
};

static float4 vert_9;
static float4 vert_68;

void vert_main()
{
    float3 vert_33 = vert_12.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = float4(vert_33.x, vert_33.y, vert_33.z, vert_9.w);
    float3 vert_44 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_12.xxx) + vert_9.xyz;
    vert_9 = float4(vert_44.x, vert_44.y, vert_44.z, vert_9.w);
    float3 vert_56 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_12.zzz) + vert_9.xyz;
    vert_9 = float4(vert_56.x, vert_56.y, vert_56.z, vert_9.w);
    float3 vert_65 = vert_9.xyz + transpose(UNITY_MATRIX_M)[3].xyz;
    vert_9 = float4(vert_65.x, vert_65.y, vert_65.z, vert_9.w);
    vert_68 = vert_9.yyyy * transpose(UNITY_MATRIX_VP)[1];
    vert_68 = (transpose(UNITY_MATRIX_VP)[0] * vert_9.xxxx) + vert_68;
    vert_9 = (transpose(UNITY_MATRIX_VP)[2] * vert_9.zzzz) + vert_68;
    gl_Position = vert_9 + transpose(UNITY_MATRIX_VP)[3];
    vert_103 = vert_105;

}

vert_Output vert(vert_Input stage_input)
{
    vert_12 = stage_input.vert_12;
    vert_105 = stage_input.vert_105;
    vert_main();
    vert_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vert_103 = vert_103;
    return stage_output;
}

static float4 frag_9;

struct frag_Output
{
    float4 frag_9 : SV_Target0;
};

void frag_main()
{
    frag_9 = 0.0f.xxxx;
}

frag_Output frag()
{
    frag_main();
    frag_Output stage_output;
    stage_output.frag_9 = frag_9;
    return stage_output;
}

ENDHLSL
}

Pass {
Name "DepthNormalsOnly"
Tags { "LightMode"="DepthNormalsOnly" }
ZTest LEqual
ZWrite On
Cull [_Cull]
ColorMask RGBA
HLSLPROGRAM
#pragma target 4.5
#pragma vertex vert
#pragma fragment frag
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
float4 _ShadowBias;
float3 _LightDirection;
CBUFFER_START(UnityPerMaterial)
float4 _MaskTex_3_TexelSize;
float _1;
float _Is_Eye;
float4 _Rim_Color;
float _RimStrength_3;
float4 _MainTex_TexelSize;
float4 _MaskTex_TexelSize;
float _RimStrength;
float _RimPower;
float _LightDirectionStrength;
float3 _Light_Angle;
float4 _Shadow_Color;
float _Brightness;
float _Shadow_Threshould;
float3 _PrimaryLightDirection;
float3 _PrimaryLightColor;
float _PrimaryLightIntensity;
float _RimThreshould;
float _RimSoftness;
float4 _ambientColor;
float _ambientIntensity;
CBUFFER_END



static float4 gl_Position;
static float3 vert_12;
static float4 vert_104;
static float4 vert_147;
static float4 vert_161;
static float4 vert_162;
static float3 vert_164;
static float3 vert_194;

struct vert_Input
{
    float3 vert_12 : POSITION;
    float3 vert_164 : NORMAL;
    float4 vert_104 : TANGENT;
    float4 vert_162 : TEXCOORD0;
};

struct vert_Output
{
    float3 vert_194 : TEXCOORD0;
    float4 vert_147 : TEXCOORD1;
    float4 vert_161 : TEXCOORD2;
    float4 gl_Position : SV_Position;
};

static float4 vert_9;
static float4 vert_68;
static float vert_136;

void vert_main()
{
    float3 vert_33 = vert_12.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = float4(vert_33.x, vert_33.y, vert_33.z, vert_9.w);
    float3 vert_44 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_12.xxx) + vert_9.xyz;
    vert_9 = float4(vert_44.x, vert_44.y, vert_44.z, vert_9.w);
    float3 vert_56 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_12.zzz) + vert_9.xyz;
    vert_9 = float4(vert_56.x, vert_56.y, vert_56.z, vert_9.w);
    float3 vert_65 = vert_9.xyz + transpose(UNITY_MATRIX_M)[3].xyz;
    vert_9 = float4(vert_65.x, vert_65.y, vert_65.z, vert_9.w);
    vert_68 = vert_9.yyyy * transpose(UNITY_MATRIX_VP)[1];
    vert_68 = (transpose(UNITY_MATRIX_VP)[0] * vert_9.xxxx) + vert_68;
    vert_9 = (transpose(UNITY_MATRIX_VP)[2] * vert_9.zzzz) + vert_68;
    gl_Position = vert_9 + transpose(UNITY_MATRIX_VP)[3];
    float3 vert_110 = vert_104.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = float4(vert_110.x, vert_110.y, vert_110.z, vert_9.w);
    float3 vert_121 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_104.xxx) + vert_9.xyz;
    vert_9 = float4(vert_121.x, vert_121.y, vert_121.z, vert_9.w);
    float3 vert_132 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_104.zzz) + vert_9.xyz;
    vert_9 = float4(vert_132.x, vert_132.y, vert_132.z, vert_9.w);
    vert_136 = dot(vert_9.xyz, vert_9.xyz);
    vert_136 = max(vert_136, 1.1754943508222875079687365372222e-38f);
    vert_136 = rsqrt(vert_136);
    float3 vert_152 = vert_136.xxx * vert_9.xyz;
    vert_147 = float4(vert_152.x, vert_152.y, vert_152.z, vert_147.w);
    vert_147.w = vert_104.w;
    vert_161 = vert_162;
    vert_9.x = dot(vert_164, transpose(UNITY_MATRIX_I_M)[0].xyz);
    vert_9.y = dot(vert_164, transpose(UNITY_MATRIX_I_M)[1].xyz);
    vert_9.z = dot(vert_164, transpose(UNITY_MATRIX_I_M)[2].xyz);
    vert_136 = dot(vert_9.xyz, vert_9.xyz);
    vert_136 = max(vert_136, 1.1754943508222875079687365372222e-38f);
    vert_136 = rsqrt(vert_136);
    vert_194 = vert_136.xxx * vert_9.xyz;

}

vert_Output vert(vert_Input stage_input)
{
    vert_12 = stage_input.vert_12;
    vert_104 = stage_input.vert_104;
    vert_162 = stage_input.vert_162;
    vert_164 = stage_input.vert_164;
    vert_main();
    vert_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vert_147 = vert_147;
    stage_output.vert_161 = vert_161;
    stage_output.vert_194 = vert_194;
    return stage_output;
}

static float3 frag_11;
static float4 frag_29;

struct frag_Input
{
    float3 frag_11 : TEXCOORD0;
};

struct frag_Output
{
    float4 frag_29 : SV_Target0;
};

static float3 frag_9;

void frag_main()
{
    frag_9.x = dot(frag_11, frag_11);
    frag_9.x = rsqrt(frag_9.x);
    frag_9 = frag_9.xxx * frag_11;
    frag_29 = float4(frag_9.x, frag_9.y, frag_9.z, frag_29.w);
    frag_29.w = 0.0f;
}

frag_Output frag(frag_Input stage_input)
{
    frag_11 = stage_input.frag_11;
    frag_main();
    frag_Output stage_output;
    stage_output.frag_29 = frag_29;
    return stage_output;
}

ENDHLSL
}

Pass {
Name "ShadowCaster"
Tags { "LightMode"="ShadowCaster" }
ZTest LEqual
ZWrite On
Cull [_Cull]
ColorMask 0
HLSLPROGRAM
#pragma target 4.5
#pragma vertex vert
#pragma fragment frag
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
float4 _ShadowBias;
float3 _LightDirection;
CBUFFER_START(UnityPerMaterial)
float4 _MaskTex_3_TexelSize;
float _1;
float _Is_Eye;
float4 _Rim_Color;
float _RimStrength_3;
float4 _MainTex_TexelSize;
float4 _MaskTex_TexelSize;
float _RimStrength;
float _RimPower;
float _LightDirectionStrength;
float3 _Light_Angle;
float4 _Shadow_Color;
float _Brightness;
float _Shadow_Threshould;
float3 _PrimaryLightDirection;
float3 _PrimaryLightColor;
float _PrimaryLightIntensity;
float _RimThreshould;
float _RimSoftness;
float4 _ambientColor;
float _ambientIntensity;
CBUFFER_END



static float4 gl_Position;
static float3 vert_12;
static float3 vert_85;
static float3 vert_153;
static float4 vert_194;
static float4 vert_196;

struct vert_Input
{
    float3 vert_12 : POSITION;
    float3 vert_85 : NORMAL;
    float4 vert_196 : TEXCOORD0;
};

struct vert_Output
{
    float4 vert_194 : TEXCOORD0;
    float3 vert_153 : TEXCOORD1;
    float4 gl_Position : SV_Position;
};

static float4 vert_9;
static float4 vert_84;
static float vert_107;

void vert_main()
{
    float3 vert_33 = vert_12.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = float4(vert_33.x, vert_33.y, vert_33.z, vert_9.w);
    float3 vert_44 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_12.xxx) + vert_9.xyz;
    vert_9 = float4(vert_44.x, vert_44.y, vert_44.z, vert_9.w);
    float3 vert_56 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_12.zzz) + vert_9.xyz;
    vert_9 = float4(vert_56.x, vert_56.y, vert_56.z, vert_9.w);
    float3 vert_65 = vert_9.xyz + transpose(UNITY_MATRIX_M)[3].xyz;
    vert_9 = float4(vert_65.x, vert_65.y, vert_65.z, vert_9.w);
    float3 vert_81 = (_LightDirection * _ShadowBias.xxx) + vert_9.xyz;
    vert_9 = float4(vert_81.x, vert_81.y, vert_81.z, vert_9.w);
    vert_84.x = dot(vert_85, transpose(UNITY_MATRIX_I_M)[0].xyz);
    vert_84.y = dot(vert_85, transpose(UNITY_MATRIX_I_M)[1].xyz);
    vert_84.z = dot(vert_85, transpose(UNITY_MATRIX_I_M)[2].xyz);
    vert_107 = dot(vert_84.xyz, vert_84.xyz);
    vert_107 = max(vert_107, 1.1754943508222875079687365372222e-38f);
    vert_107 = rsqrt(vert_107);
    float3 vert_122 = vert_107.xxx * vert_84.xyz;
    vert_84 = float4(vert_122.x, vert_122.y, vert_122.z, vert_84.w);
    vert_107 = dot(_LightDirection, vert_84.xyz);
    vert_107 = clamp(vert_107, 0.0f, 1.0f);
    vert_107 = (-vert_107) + 1.0f;
    vert_107 *= _ShadowBias.y;
    float3 vert_149 = (vert_84.xyz * vert_107.xxx) + vert_9.xyz;
    vert_9 = float4(vert_149.x, vert_149.y, vert_149.z, vert_9.w);
    vert_153 = vert_84.xyz;
    vert_84 = vert_9.yyyy * transpose(UNITY_MATRIX_VP)[1];
    vert_84 = (transpose(UNITY_MATRIX_VP)[0] * vert_9.xxxx) + vert_84;
    vert_9 = (transpose(UNITY_MATRIX_VP)[2] * vert_9.zzzz) + vert_84;
    vert_9 += transpose(UNITY_MATRIX_VP)[3];
    #if UNITY_REVERSED_Z
    gl_Position.z = min(vert_9.z, 1.0f);
    #else
    gl_Position.z = max(vert_9.z, UNITY_NEAR_CLIP_VALUE);
    #endif
    gl_Position = float4(vert_9.xyw.x, vert_9.xyw.y, gl_Position.z, vert_9.xyw.z);
    vert_194 = vert_196;

}

vert_Output vert(vert_Input stage_input)
{
    vert_12 = stage_input.vert_12;
    vert_85 = stage_input.vert_85;
    vert_196 = stage_input.vert_196;
    vert_main();
    vert_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vert_153 = vert_153;
    stage_output.vert_194 = vert_194;
    return stage_output;
}

static float4 frag_9;

struct frag_Output
{
    float4 frag_9 : SV_Target0;
};

void frag_main()
{
    frag_9 = 0.0f.xxxx;
}

frag_Output frag()
{
    frag_main();
    frag_Output stage_output;
    stage_output.frag_9 = frag_9;
    return stage_output;
}

ENDHLSL
}

Pass {
Name "DepthNormals"
Tags { "LightMode"="DepthNormalsOnly" }
ZTest LEqual
ZWrite On
Cull [_Cull]
ColorMask RGBA
HLSLPROGRAM
#pragma target 4.5
#pragma vertex vert
#pragma fragment frag
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
float4 _ShadowBias;
float3 _LightDirection;
CBUFFER_START(UnityPerMaterial)
float4 _MaskTex_3_TexelSize;
float _1;
float _Is_Eye;
float4 _Rim_Color;
float _RimStrength_3;
float4 _MainTex_TexelSize;
float4 _MaskTex_TexelSize;
float _RimStrength;
float _RimPower;
float _LightDirectionStrength;
float3 _Light_Angle;
float4 _Shadow_Color;
float _Brightness;
float _Shadow_Threshould;
float3 _PrimaryLightDirection;
float3 _PrimaryLightColor;
float _PrimaryLightIntensity;
float _RimThreshould;
float _RimSoftness;
float4 _ambientColor;
float _ambientIntensity;
CBUFFER_END



static float4 gl_Position;
static float3 vert_12;
static float4 vert_103;
static float4 vert_105;
static float3 vert_107;
static float3 vert_140;

struct vert_Input
{
    float3 vert_12 : POSITION;
    float3 vert_107 : NORMAL;
    float4 vert_105 : TEXCOORD0;
};

struct vert_Output
{
    float3 vert_140 : TEXCOORD0;
    float4 vert_103 : TEXCOORD1;
    float4 gl_Position : SV_Position;
};

static float4 vert_9;
static float4 vert_68;
static float vert_128;

void vert_main()
{
    float3 vert_33 = vert_12.yyy * transpose(UNITY_MATRIX_M)[1].xyz;
    vert_9 = float4(vert_33.x, vert_33.y, vert_33.z, vert_9.w);
    float3 vert_44 = (transpose(UNITY_MATRIX_M)[0].xyz * vert_12.xxx) + vert_9.xyz;
    vert_9 = float4(vert_44.x, vert_44.y, vert_44.z, vert_9.w);
    float3 vert_56 = (transpose(UNITY_MATRIX_M)[2].xyz * vert_12.zzz) + vert_9.xyz;
    vert_9 = float4(vert_56.x, vert_56.y, vert_56.z, vert_9.w);
    float3 vert_65 = vert_9.xyz + transpose(UNITY_MATRIX_M)[3].xyz;
    vert_9 = float4(vert_65.x, vert_65.y, vert_65.z, vert_9.w);
    vert_68 = vert_9.yyyy * transpose(UNITY_MATRIX_VP)[1];
    vert_68 = (transpose(UNITY_MATRIX_VP)[0] * vert_9.xxxx) + vert_68;
    vert_9 = (transpose(UNITY_MATRIX_VP)[2] * vert_9.zzzz) + vert_68;
    gl_Position = vert_9 + transpose(UNITY_MATRIX_VP)[3];
    vert_103 = vert_105;
    vert_9.x = dot(vert_107, transpose(UNITY_MATRIX_I_M)[0].xyz);
    vert_9.y = dot(vert_107, transpose(UNITY_MATRIX_I_M)[1].xyz);
    vert_9.z = dot(vert_107, transpose(UNITY_MATRIX_I_M)[2].xyz);
    vert_128 = dot(vert_9.xyz, vert_9.xyz);
    vert_128 = max(vert_128, 1.1754943508222875079687365372222e-38f);
    vert_128 = rsqrt(vert_128);
    vert_140 = vert_128.xxx * vert_9.xyz;

}

vert_Output vert(vert_Input stage_input)
{
    vert_12 = stage_input.vert_12;
    vert_105 = stage_input.vert_105;
    vert_107 = stage_input.vert_107;
    vert_main();
    vert_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.vert_103 = vert_103;
    stage_output.vert_140 = vert_140;
    return stage_output;
}

static float3 frag_11;
static float4 frag_29;

struct frag_Input
{
    float3 frag_11 : TEXCOORD0;
};

struct frag_Output
{
    float4 frag_29 : SV_Target0;
};

static float3 frag_9;

void frag_main()
{
    frag_9.x = dot(frag_11, frag_11);
    frag_9.x = rsqrt(frag_9.x);
    frag_9 = frag_9.xxx * frag_11;
    frag_29 = float4(frag_9.x, frag_9.y, frag_9.z, frag_29.w);
    frag_29.w = 0.0f;
}

frag_Output frag(frag_Input stage_input)
{
    frag_11 = stage_input.frag_11;
    frag_main();
    frag_Output stage_output;
    stage_output.frag_29 = frag_29;
    return stage_output;
}

ENDHLSL
}

}
Fallback Off
}
